name: Dependency Check

on:
  pull_request

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.3
    env:
      ALERT_ON: "MEDIUM,HIGH,CRITICAL" # Options: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}
          
      - name: Check for Dependency Lock File Changes
        id: check-changes
        shell: bash
        run: |
          watched_files=("config.json" "application.conf")
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            # For pull requests, use 'before' and 'after' from GitHub context for comparison
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          else
            # For other events (e.g., push), use the commit range from GitHub context or specific commits
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          fi
  
          echo "Changed files: $changed_files"
          
      - name: Install Trivy Scanner
        run: |
          TRIVY_VERSION="0.59.1"
          REPOSITORY="aquasecurity/trivy"
          BASE_URL="https://github.com/${REPOSITORY}/releases/download/v${TRIVY_VERSION}"
          
          curl -L -o trivy.tar.gz "$BASE_URL/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz"
          curl -L -o trivy_checksums.txt "$BASE_URL/trivy_${TRIVY_VERSION}_checksums.txt"
          
          EXPECTED_CHECKSUM=$(grep "trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz" trivy_checksums.txt | awk '{print $1}')
          echo "$EXPECTED_CHECKSUM  trivy.tar.gz" | sha256sum -c -
          
          tar -xzf trivy.tar.gz -C /usr/local/bin
          trivy --version

      - name: Specify Git Safe Directories
        run: |
          git config --global --add safe.directory "*"
      - name: Checkout Default Branch
        run: |
          git fetch origin main
          git checkout origin/main
      
      - name: Run Trivy (Default Branch)
        id: trivy-default-branch-scan
        run: |
          trivy repo --quiet --scanners vuln --pkg-types library -s "$ALERT_ON" --format json . > default_branch_vulnerabilities.json
          
      - name: Checkout Pull Request Branch
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
      
      - name: Run Trivy (Pull Request Branch)
        id: trivy-pull-request-branch-scan
        run: |
          trivy repo --quiet --scanners vuln --pkg-types library -s "$ALERT_ON" --format json . > pr_branch_vulnerabilities.json
      
      - name: Analyze Scan Results
        id: analyze-scan-results
        run: |
          ruby .github/scripts/dependency_check.rb
